MODELS:
  WavTokenizer-medium-music-75token:
    config: wavtokenizer_smalldata_frame75_3s_nq1_code4096_dim512_kmeans200_attn.yaml
    checkpoint: novateur/WavTokenizer-medium-music-audio-75token/wavtokenizer_medium_music_audio_320_24k_v2.ckpt
  WavTokenizer-large-unify-40token:
    config: wavtokenizer_smalldata_frame40_3s_nq1_code4096_dim512_kmeans200_attn.yaml
    checkpoint: novateur/WavTokenizer-large-unify-40token/wavtokenizer_large_unify_600_24k.ckpt
    
